name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Check if maintainer
        env:
          GITHUB_PR_USER: ${{ github.actor }}
        run: |
          python is_maintainer.py;
          exit $?;
      - name: Auto-merge PR
        id: automerge
        if: success()
        uses: "whoopnip/automerge-action@merged-to-use-temporarily"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!no auto merge"
          UPDATE_LABELS: "!no auto merge"
      - name: Stop if Not Merged
        run: |
          if $PR_WAS_MERGED; then
            echo "PR was merged, now need to deploy"
            exit 0;
          fi;
          echo "PR was not merged, will not auto-deploy"
          exit 1;
        env:
          PR_WAS_MERGED: ${{ steps.automerge.outputs.merged }}

  # TODO [$5dfce3ece3afb90007e9f662]: refactor auto-merge workflow once Github Actions improves
  #
  # Entire jobs are getting copied between workflow files due to limitations in Github Actions.
  # The only difference in these jobs is that they checkout master instead of requiring master
  #
  # Possible changes to Github Actions that would allow the automerge workflow to be refactored:
  # - reuse jobs
  # - reuse steps
  # - trigger workflow from within action/workflow
  # - commit triggered by action triggers push event
  collectTODO:
    needs: automerge
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
      - name: Collect TODO
        uses: whoopnip/todo-actions@input-commit-branch
        with:
          commitBranch: master
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}

  updateReleaseDraft:
    needs: automerge
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
